itemsA = {"蘋果", "香蕉", "鳳梨", "芭樂"}  # 這是第一個集合
itemsB = {"鳳梨", "蘋果", "水梨", "蓮霧"}  # 這是第二個集合
itemsA.add(input())
itemsA.add(input())
itemsA.remove("蘋果")
itemsB.add(input())
itemsB.add(input())
itemsB.remove("蓮霧")
iA = list(itemsA)
iA.sort()
iB = list(itemsB)
iB.sort()
union = list(itemsA | itemsB)
union.sort()
intersect = list(itemsA & itemsB)
intersect.sort()
Adiff = list(itemsA - itemsB)
Adiff.sort()
Bdiff = list(itemsB - itemsA)
Bdiff.sort()
xOR = list(itemsA ^ itemsB)
xOR.sort()
print("iA: "+str(iA))
print("iB: "+str(iB))
print("union: "+str(union))
print("intersection: "+str(intersect))
print("A diff B: "+str(Adiff))
print("B diff A: "+str(Bdiff))
print("A xor B: "+str(xOR))

